#!/usr/bin/expect


system echo
system echo "RMB promts ARE echoed"

spawn ./p3
#spawn ./t3

expect "_sh> "
send "echo STARTING\r"

expect "_sh> "
send "src s1\r"

expect "_sh> "
send "echo DONE\r"

expect "_sh> "
send "quit\r"

system echo
system echo "RMB promts ARE echoed"
